# Generated by Django 4.1.4 on 2023-01-01 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_urls', '0002_alter_url_tiny_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='original_url',
            field=models.URLField(validators=[django.core.validators.URLValidator(regex='^https?://')]),
        ),
    ]
