# Generated by Django 4.1.4 on 2023-01-03 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_urls', '0003_alter_url_original_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='original_url',
            field=models.URLField(validators=[django.core.validators.URLValidator()]),
        ),
    ]
